In [1]:
# !pip install akshare -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host=mirrors.aliyun.com  --upgrade --user

In [2]:
!pip install akshare --upgrade -i https://pypi.org/simple

Collecting akshare

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] 拒绝访问。: 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\akshare\\datasets.py'
Consider using the `--user` option or check the permissions.

  Downloading akshare-1.9.10-py3-none-any.whl (976 kB)
Requirement already satisfied, skipping upgrade: tabulate>=0.8.6 in c:\programdata\anaconda3\lib\site-packages (from akshare) (0.9.0)
Requirement already satisfied, skipping upgrade: tqdm>=4.43.0 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from akshare) (4.64.0)
Requirement already satisfied, skipping upgrade: requests-cache>=0.9.3 in c:\programdata\anaconda3\lib\site-packages (from akshare) (0.9.8)
Requirement already satisfied, skipping upgrade: xlrd>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from akshare) (1.2.0)
Requirement already satisfied, skipping upgrade: urllib3>=1.25.8 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from akshare) (1.26.11)
Requirement already satisfied, skipping upgrade: pandas>=0.25 in c:\programdata\anaconda3\lib\site-packages (from akshare) (1.0.5)
Requirement already satisfied, skipping upgrade: openpyxl>=3.0.3 in c:\programdata\anaconda3\lib\site-packages (from akshare) (3.0.4)
Requirement already satisfied, skipping upgrade: jsonpath>=0.82 in c:\programdata\anaconda3\lib\site-packages (from akshare) (0.82)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.9.1 in c:\programdata\anaconda3\lib\site-packages (from akshare) (4.9.1)
Requirement already satisfied, skipping upgrade: decorator>=4.4.2 in c:\programdata\anaconda3\lib\site-packages (from akshare) (4.4.2)
Requirement already satisfied, skipping upgrade: py-mini-racer>=0.6.0 in c:\programdata\anaconda3\lib\site-packages (from akshare) (0.6.0)
Requirement already satisfied, skipping upgrade: pypinyin>=0.35.0 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from akshare) (0.47.0)
Requirement already satisfied, skipping upgrade: cfscrape>=2.1.1 in c:\programdata\anaconda3\lib\site-packages (from akshare) (2.1.1)
Requirement already satisfied, skipping upgrade: requests>=2.22.0 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from akshare) (2.28.1)
Requirement already satisfied, skipping upgrade: websocket-client>=0.56.0 in c:\programdata\anaconda3\lib\site-packages (from akshare) (0.57.0)
Requirement already satisfied, skipping upgrade: lxml>=4.2.1 in c:\programdata\anaconda3\lib\site-packages (from akshare) (4.5.2)
Requirement already satisfied, skipping upgrade: html5lib>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from akshare) (1.1)
Requirement already satisfied, skipping upgrade: colorama; platform_system == "Windows" in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from tqdm>=4.43.0->akshare) (0.4.5)
Requirement already satisfied, skipping upgrade: attrs>=21.2 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from requests-cache>=0.9.3->akshare) (22.1.0)
Requirement already satisfied, skipping upgrade: cattrs>=22.2 in c:\programdata\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare) (22.2.0)
Requirement already satisfied, skipping upgrade: appdirs>=1.4.4 in c:\programdata\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare) (1.4.4)
Requirement already satisfied, skipping upgrade: url-normalize>=1.4 in c:\programdata\anaconda3\lib\site-packages (from requests-cache>=0.9.3->akshare) (1.4.3)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.25->akshare) (2020.1)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from pandas>=0.25->akshare) (1.21.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from pandas>=0.25->akshare) (2.8.2)
Requirement already satisfied, skipping upgrade: jdcal in c:\programdata\anaconda3\lib\site-packages (from openpyxl>=3.0.3->akshare) (1.4.1)
Requirement already satisfied, skipping upgrade: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl>=3.0.3->akshare) (1.0.1)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4>=4.9.1->akshare) (2.0.1)
Requirement already satisfied, skipping upgrade: idna<4,>=2.5 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from requests>=2.22.0->akshare) (3.3)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from requests>=2.22.0->akshare) (2022.6.15)
Requirement already satisfied, skipping upgrade: charset-normalizer<3,>=2 in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from requests>=2.22.0->akshare) (2.1.0)
Requirement already satisfied, skipping upgrade: six in c:\users\lhhriver\appdata\roaming\python\python38\site-packages (from websocket-client>=0.56.0->akshare) (1.16.0)
Requirement already satisfied, skipping upgrade: webencodings in c:\programdata\anaconda3\lib\site-packages (from html5lib>=1.0.1->akshare) (0.5.1)
Requirement already satisfied, skipping upgrade: exceptiongroup; python_version < "3.11" in c:\programdata\anaconda3\lib\site-packages (from cattrs>=22.2->requests-cache>=0.9.3->akshare) (1.1.0)
Installing collected packages: akshare
  Attempting uninstall: akshare
    Found existing installation: akshare 1.8.84
    Uninstalling akshare-1.8.84:
      Successfully uninstalled akshare-1.8.84
  Rolling back uninstall of akshare
  Moving to c:\users\lhhriver\appdata\roaming\python\python38\site-packages\akshare-1.8.84.dist-info\
   from C:\Users\lhhriver\AppData\Roaming\Python\Python38\site-packages\~kshare-1.8.84.dist-info
  Moving to c:\users\lhhriver\appdata\roaming\python\python38\site-packages\akshare\
   from C:\Users\lhhriver\AppData\Roaming\Python\Python38\site-packages\~kshare
  Moving to c:\users\lhhriver\appdata\roaming\python\python38\site-packages\tests\
   from C:\Users\lhhriver\AppData\Roaming\Python\Python38\site-packages\~ests

# 导入包

In [3]:
import os
import sys
import pandas as pd
import numpy as np
import akshare as ak
import datetime

# 日期处理

In [4]:
yesterday = (datetime.datetime.now() - datetime.timedelta(days=1)).strftime('%Y%m%d')
yesterday

'20230314'

In [5]:
today_ = datetime.datetime.now().strftime('%Y-%m-%d')
today = datetime.datetime.now().strftime('%Y%m%d')
today_, today

('2023-03-15', '20230315')

In [6]:
b_100_day = (datetime.datetime.now() - datetime.timedelta(days=100)).strftime('%Y%m%d')
stock_zh_tmp = ak.stock_zh_a_hist(symbol="688517",
                                  period="daily",
                                  start_date=b_100_day,
                                  end_date=today,
                                  adjust="")
stock_zh_tmp = stock_zh_tmp.loc[stock_zh_tmp['日期'] != datetime.datetime.now().strftime('%Y-%m-%d')]
b_60_day = stock_zh_tmp[['日期']].tail(60).iloc[0, 0].replace("-", "")
b_60_day

'20221213'

In [7]:
# day1 = stock_zh_tmp[['日期']].tail(2).values.tolist()[0][0].replace("-", "")
# day2 = stock_zh_tmp[['日期']].tail(2).values.tolist()[1][0].replace("-", "")

last_day_ = stock_zh_tmp[['日期']].tail(1).iloc[0, 0]
last_day = stock_zh_tmp[['日期']].tail(1).iloc[0, 0].replace("-", "")
last_day_, last_day

('2023-03-14', '20230314')

# 数据获取

## 个股查询

In [8]:
stock_individual_info_em_df = ak.stock_individual_info_em(symbol="000001")
stock_individual_info_em_df

   item        value
0   总市值  2.52471e+11
1  流通市值  2.52466e+11
2    行业           银行
3  上市时间     19910403
4  股票代码       000001
5  股票简称         平安银行
6   总股本  1.94059e+10
7   流通股  1.94055e+10

## 行业版块

In [9]:
industry_df = stock_board_industry_name_em_df = ak.stock_board_industry_name_ths()
industry_df.columns = ['版块', '版块代码']
industry_df

         版块    版块代码
0    种植业与林业  881101
1       养殖业  881102
2     农产品加工  881103
3      农业服务  881104
4    煤炭开采加工  881105
..      ...     ...
301  综合环境治理  884270
302    个护用品  884271
303     化妆品  884272
304    医疗美容  884273
305    IT服务  884274

[306 rows x 2 columns]

In [10]:
# stock_board_cons_ths_df = pd.DataFrame()

# for dt in industry_df.to_dict(orient="record")[:]:
#     stock_board_cons_ths_df_tmp = ak.stock_board_cons_ths(symbol=dt['版块代码'])
#     # print(stock_board_cons_ths_df_tmp.shape)
#     stock_board_cons_ths_df_tmp['版块'] = dt['版块']
#     stock_board_cons_ths_df_tmp['版块代码'] = dt['版块代码']

#     stock_board_cons_ths_df = stock_board_cons_ths_df.append(stock_board_cons_ths_df_tmp)

# stock_board_cons_ths_df = stock_board_cons_ths_df[[
#     '序号', '代码', '名称', '版块', '版块代码', '现价', '涨跌幅', '涨跌', '涨速', '换手', '量比', '振幅',
#     '成交额', '流通股', '流通市值', '市盈率'
# ]]
# stock_board_cons_ths_df.to_excel("stock_board_cons_ths_df.xlsx", index=False)
# stock_board_cons_ths_df

In [11]:
import tushare as ts

ts.set_token('a8e53ab4da4f693e211284520f4b8b597f4784494b812f68668afbb3')
pro = ts.pro_api()

In [12]:
data_list_df = pro.query('stock_basic',
                         exchange='',
                         list_status='L',
                         fields='symbol,name,area,industry,market,list_date')
data_list_df.columns = ["代码", "名称", "地区", "行业", "版块", "上市日期"]
data_list_df

          代码       名称    地区    行业   版块      上市日期
0     000001     平安银行    深圳    银行   主板  19910403
1     000002      万科A    深圳  全国地产   主板  19910129
2     000004     ST国华    深圳  软件服务   主板  19910114
3     000005     ST星源    深圳  环境保护   主板  19901210
4     000006     深振业A    深圳  区域地产   主板  19920427
...      ...      ...   ...   ...  ...       ...
5114  873223     荣亿精密  None  None  北交所  20220609
5115  873305     九菱科技  None  None  北交所  20221221
5116  873339     恒太照明  None  None  北交所  20221117
5117  873527      夜光明  None  None  北交所  20221027
5118  689009  九号公司-WD    北京   摩托车  CDR  20201029

[5119 rows x 6 columns]

## 实时行情

### 沪深京 A 股

In [13]:
# stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em()
# stock_zh_a_spot_em_df.sample(5)

In [14]:
# stock_zh_a_spot_em_df.shape

### 沪 A 股

In [15]:
stock_sh_a_spot_em_df = ak.stock_sh_a_spot_em()
stock_sh_a_spot_em_df.head(5)

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,603282,N亚光,25.92,44.00,7.92,5744.0,14808174.0,24.00,25.92,...,NaN,1.71,20.70,3.17,3.468614e+09,8.683200e+08,0.00,0.00,44.00,44.00
1,2,600800,渤海化学,4.26,10.08,0.39,421199.0,176658634.0,8.53,4.26,...,12.75,5.30,-132.11,1.74,5.051455e+09,3.383877e+09,0.47,0.47,9.23,17.36
2,3,600469,风神股份,5.80,10.06,0.53,136935.0,76781508.0,10.06,5.80,...,4.12,2.44,50.08,1.52,4.230815e+09,3.252216e+09,0.00,0.00,15.54,23.67
3,4,603578,三星新材,14.69,10.04,1.34,32035.0,45688585.0,9.89,14.69,...,6.01,1.78,21.31,2.73,2.649445e+09,2.649445e+09,0.00,0.00,12.91,18.09
4,5,603699,纽威股份,14.04,10.03,1.28,91777.0,126908998.0,7.76,14.04,...,2.64,1.23,22.75,3.36,1.051683e+10,1.051683e+10,0.00,0.00,25.36,26.49

### 深 A 股

In [16]:
stock_sz_a_spot_em_df = ak.stock_sz_a_spot_em()
stock_sz_a_spot_em_df.head(5)

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,300181,佐力药业,14.23,15.60,1.92,464768.0,6.415712e+08,8.37,14.35,...,6.38,7.64,35.97,3.68,9.980742e+09,8.660732e+09,0.35,0.42,25.82,33.36
1,2,300582,英飞特,16.04,11.85,1.70,272190.0,4.286230e+08,14.99,16.50,...,4.40,12.38,23.38,2.85,4.765627e+09,3.526702e+09,0.88,0.94,20.78,27.40
2,3,300423,昇辉科技,14.22,11.79,1.50,125766.0,1.721857e+08,11.79,14.25,...,3.85,3.98,36.81,1.64,7.074611e+09,4.494720e+09,0.14,0.14,36.21,52.41
3,4,300912,凯龙高科,28.30,11.55,2.93,132463.0,3.631266e+08,12.89,28.86,...,1.67,21.51,-30.62,3.25,3.255123e+09,1.743080e+09,0.04,0.21,83.41,109.47
4,5,000506,中润资源,4.59,10.07,0.42,1814772.0,7.872364e+08,13.19,4.59,...,3.35,19.54,15.37,7.23,4.264192e+09,4.262600e+09,0.00,0.00,34.60,42.11

### 京 A 股

In [17]:
# stock_bj_a_spot_em_df = ak.stock_bj_a_spot_em()
# stock_bj_a_spot_em_df.head(5)

### 沪深A股

In [18]:
stock_df_ss = stock_sh_a_spot_em_df.append(stock_sz_a_spot_em_df)
flag_ss = stock_df_ss['代码'].str.startswith("0") | stock_df_ss['代码'].str.startswith("6")
stock_df_ss = stock_df_ss[flag_ss]
stock_df_ss = stock_df_ss[stock_df_ss['最新价'] - stock_df_ss['今开'] > 0]
stock_df_ss

,序号,代码,名称,最新价,涨跌幅,涨跌额,成交量,成交额,振幅,最高,...,量比,换手率,市盈率-动态,市净率,总市值,流通市值,涨速,5分钟涨跌,60日涨跌幅,年初至今涨跌幅
0,1,603282,N亚光,25.92,44.00,7.92,5744.0,1.480817e+07,24.00,25.92,...,NaN,1.71,20.70,3.17,3.468614e+09,8.683200e+08,0.00,0.00,44.00,44.00
1,2,600800,渤海化学,4.26,10.08,0.39,421199.0,1.766586e+08,8.53,4.26,...,12.75,5.30,-132.11,1.74,5.051455e+09,3.383877e+09,0.47,0.47,9.23,17.36
2,3,600469,风神股份,5.80,10.06,0.53,136935.0,7.678151e+07,10.06,5.80,...,4.12,2.44,50.08,1.52,4.230815e+09,3.252216e+09,0.00,0.00,15.54,23.67
3,4,603578,三星新材,14.69,10.04,1.34,32035.0,4.568858e+07,9.89,14.69,...,6.01,1.78,21.31,2.73,2.649445e+09,2.649445e+09,0.00,0.00,12.91,18.09
4,5,603699,纽威股份,14.04,10.03,1.28,91777.0,1.269090e+08,7.76,14.04,...,2.64,1.23,22.75,3.36,1.051683e+10,1.051683e+10,0.00,0.00,25.36,26.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2686,2687,003026,中晶科技,50.58,-1.52,-0.78,36247.0,1.843093e+08,3.23,51.66,...,2.12,6.56,157.28,6.84,5.109484e+09,2.794912e+09,-0.14,-0.18,13.84,4.50
2813,2814,000017,深中华A,4.67,-2.91,-0.14,199304.0,9.209631e+07,4.37,4.72,...,3.76,6.58,1991.95,10.77,3.218494e+09,1.414921e+09,-0.21,0.00,-7.71,-1.89
2834,2835,002089,*ST新海,1.10,-3.51,-0.04,1999634.0,2.206557e+08,7.89,1.17,...,3.92,16.04,114.89,1.21,1.512137e+09,1.371483e+09,0.00,-0.90,-51.75,-48.11
2847,2848,001278,一彬科技,26.28,-4.51,-1.24,93923.0,2.441099e+08,5.89,27.05,...,2.51,30.36,28.93,2.71,3.251714e+09,8.129298e+08,-0.45,-0.87,54.59,54.59
2853,2854,001368,通达创智,30.57,-6.14,-2.00,65259.0,1.989740e+08,3.62,31.31,...,1.72,23.31,26.01,2.58,3.423840e+09,8.559600e+08,0.13,0.07,21.65,21.65

## 历史行情数据

### 历史行情数据-东财

In [19]:
# stock_zh_a_hist_df_60 = pd.DataFrame()
# for code in stock_df_ss['代码'].values.tolist():
#     stock_zh_a_hist_df = ak.stock_zh_a_hist(symbol=code, period="daily", start_date=b_60_day, end_date=last_day, adjust="")
#     stock_zh_a_hist_df['代码'] = code
#     stock_zh_a_hist_df_60 = stock_zh_a_hist_df_60.append(stock_zh_a_hist_df)

# stock_zh_a_hist_df_60

In [20]:
from threading import Thread, Lock, Semaphore

sem = Semaphore(16)  # 此变量用于控制最大并发数

stock_zh_a_hist_df_60 = pd.DataFrame()


def work(eachlist, lock):
    global stock_zh_a_hist_df_60
    sem.acquire()
    stock_zh_a_hist_tmp = pd.DataFrame()
    for code in eachlist:
        stock_zh_a_hist_ = ak.stock_zh_a_hist(symbol=code,
                                              period="daily",
                                              start_date=b_60_day,
                                              end_date=last_day,
                                              adjust="")
        stock_zh_a_hist_['代码'] = code
        stock_zh_a_hist_tmp = stock_zh_a_hist_tmp.append(stock_zh_a_hist_)

    lock.acquire()
    stock_zh_a_hist_df_60 = stock_zh_a_hist_df_60.append(stock_zh_a_hist_tmp)
    lock.release()
    sem.release()


stock_list = stock_df_ss['代码'].values.tolist()
stock_epoch = [stock_list[i:i + int(len(stock_list) / 100)] for i in range(0, len(stock_list), int(len(stock_list) / 100))]

lock = Lock()

l = []
for eachlist in stock_epoch:
    p = Thread(target=work, args=(eachlist, lock))
    l.append(p)

for p in l:
    p.start()

for p in l:
    p.join()

In [21]:
stock_zh_a_hist_df_60

,代码,日期,开盘,收盘,最高,最低,成交量,成交额,振幅,涨跌幅,涨跌额,换手率
0,600800,2022-12-13,3.95,3.90,3.96,3.88,59829.0,2.336513e+07,2.05,0.00,0.00,0.75
1,600800,2022-12-14,3.90,3.87,3.92,3.86,55021.0,2.134742e+07,1.54,-0.77,-0.03,0.69
2,600800,2022-12-15,3.90,3.85,3.91,3.84,46438.0,1.796903e+07,1.81,-0.52,-0.02,0.58
3,600800,2022-12-16,3.84,3.82,3.87,3.80,49777.0,1.906816e+07,1.82,-0.78,-0.03,0.63
4,600800,2022-12-19,3.80,3.70,3.83,3.70,65400.0,2.443502e+07,3.40,-3.14,-0.12,0.82
...,...,...,...,...,...,...,...,...,...,...,...,...
55,001215,2023-03-08,74.99,78.00,79.39,74.39,13375.0,1.036742e+08,6.67,4.00,3.00,2.96
56,001215,2023-03-09,77.87,78.30,81.00,77.18,9167.0,7.217373e+07,4.90,0.38,0.30,2.03
57,001215,2023-03-10,77.18,75.50,80.45,75.38,10822.0,8.408863e+07,6.48,-3.58,-2.80,2.39
58,001215,2023-03-13,74.65,75.73,76.38,74.33,6357.0,4.773493e+07,2.72,0.30,0.23,1.41
59,001215,2023-03-14,75.70,74.44,75.70,73.90,5862.0,4.366598e+07,2.38,-1.70,-1.29,1.30

# 策略

## 上个交易日数据

In [22]:
# 昨天数据
stock_zh_a_hist_df_last_day = stock_zh_a_hist_df_60[stock_zh_a_hist_df_60['日期'] == last_day_]
stock_zh_a_hist_df_last_day = stock_zh_a_hist_df_last_day[['代码', '开盘', '收盘']]
stock_zh_a_hist_df_last_day.columns = ['代码', '昨开', '昨收']
stock_zh_a_hist_df_last_day

        代码     昨开     昨收
59  600800   3.93   3.87
59  600469   5.39   5.27
59  603578  13.30  13.35
59  603699  12.21  12.76
59  600202   5.50   5.39
..     ...    ...    ...
59  002901  38.90  39.05
59  002556   8.39   8.56
59  002385   8.05   8.15
59  002059   7.16   7.04
59  001215  75.70  74.44

[2643 rows x 3 columns]

## 60日均价

In [23]:
# 60日均价
data_avg_60 = stock_zh_a_hist_df_60[['代码', '收盘']].groupby(['代码'], as_index=False)['收盘'].mean().round(2)
data_avg_60.columns = ['代码', '收盘_60']
data_avg_60

          代码   收盘_60
0     000002   17.94
1     000004    9.83
2     000006    5.69
3     000007    7.75
4     000008    2.44
...      ...     ...
2638  688798  109.58
2639  688799   34.77
2640  688800  104.87
2641  688981   42.33
2642  689009   32.80

[2643 rows x 2 columns]

## 筛选股票

In [24]:
print(stock_df_ss.shape)
data_res_a = pd.merge(stock_df_ss[['代码', '名称', '最新价', '今开']],
                      stock_zh_a_hist_df_last_day,
                      on=['代码'],
                      how="left")
data_res_a = pd.merge(data_res_a, data_avg_60, on=['代码'], how="left")
data_res_a.columns = ['代码', '名称', '最新价', '今开', '昨开', '昨收', '收盘_60']

(2644, 23)

In [25]:
data_res_a["老A"] = (data_res_a["最新价"] - data_res_a["昨收"]) / (data_res_a["昨开"] - data_res_a["昨收"])
data_res_a["老A"] = data_res_a["老A"].round(2)
data_res_b = data_res_a[data_res_a['老A'].between(0.5, 1.5)]
print(data_res_b.shape)

(1169, 8)

In [26]:
data_res_b["老C"] = data_res_b['最新价'] / data_res_b['收盘_60']
data_res_b["老C"] = data_res_b["老C"].round(2)
data_res_c = data_res_b[data_res_b['老C'].between(0.7, 1.2)]
print(data_res_c.shape)
data_res_c

(1162, 9)

<ipython-input-26-263fc6545942>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_res_b["老C"] = data_res_b['最新价'] / data_res_b['收盘_60']
<ipython-input-26-263fc6545942>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_res_b["老C"] = data_res_b["老C"].round(2)

          代码     名称    最新价     今开     昨开     昨收  收盘_60    老A    老C
44    601872   招商轮船   7.87   7.56   7.77   7.48   6.59  1.34  1.19
46    603569   长久物流  10.10   9.68   9.95   9.61   9.37  1.44  1.08
59    688217   睿昂基因  47.09  45.63  47.36  44.93  43.97  0.89  1.07
61    603237    五芳斋  55.54  52.84  55.12  53.00  49.51  1.20  1.12
73    605100   华丰股份  14.61  14.26  14.55  13.97  14.18  1.10  1.03
...      ...    ...    ...    ...    ...    ...    ...   ...   ...
2594  000967   盈峰环境   5.21   5.20   5.22   5.20   5.03  0.50  1.04
2601  000697   炼石航空   6.24   6.23   6.24   6.23   6.98  1.00  0.89
2626  000410  *ST沈机   5.77   5.76   5.77   5.78   5.86  1.00  0.98
2637  002819   东方中科  31.16  31.15  31.20  31.51  27.79  1.13  1.12
2640  000017   深中华A   4.67   4.61   4.57   4.81   4.81  0.58  0.97

[1162 rows x 9 columns]

In [27]:
data_res_all = pd.merge(data_res_c,
                        data_list_df[["代码", "版块", "行业"]],
                        on=['代码'],
                        how="left")
data_res_all['日期'] = today
data_res_all = data_res_all[['代码', '名称', '版块', '行业', '日期', '最新价', '今开', '昨开', '昨收', '收盘_60', '老A', '老C']]
data_res_all = data_res_all.sort_values(['代码'])
data_res_all["代码"] = "\t" + data_res_all["代码"]
data_res_all.to_excel("data_res_all_" + today + ".xlsx", index=False)
data_res_all

,代码,名称,版块,行业,日期,最新价,今开,昨开,昨收,收盘_60,老A,老C
1116,\t000002,万 科Ａ,主板,全国地产,20230315,15.88,15.81,15.84,15.75,17.94,1.44,0.89
1126,\t000006,深振业Ａ,主板,区域地产,20230315,5.39,5.35,5.42,5.35,5.69,0.57,0.95
739,\t000008,神州高铁,主板,运输设备,20230315,2.50,2.44,2.49,2.44,2.44,1.20,1.02
1006,\t000009,中国宝安,主板,电气设备,20230315,11.89,11.73,11.95,11.74,12.41,0.71,0.96
836,\t000010,美丽生态,主板,建筑工程,20230315,3.21,3.15,3.22,3.15,3.50,0.86,0.92
...,...,...,...,...,...,...,...,...,...,...,...,...
323,\t688733,壹石通,科创板,矿物制品,20230315,38.09,37.76,38.20,37.49,40.27,0.85,0.95
200,\t688778,厦钨新能,科创板,电气设备,20230315,73.49,72.49,73.03,72.10,81.75,1.49,0.90
630,\t688789,宏华数科,科创板,专用机械,20230315,188.90,188.50,189.49,187.91,179.70,0.63,1.05
500,\t688800,瑞可达,科创板,元器件,20230315,84.33,83.50,84.36,83.40,104.87,0.97,0.80
269,\t689009,九号公司-WD,CDR,摩托车,20230315,32.43,32.16,32.33,31.88,32.80,1.22,0.99